<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>main_Learn to code  for free.Build projects_872dbd</name>
   <tag></tag>
   <elementGuidId>4b0dec30-5a64-4066-8d98-39f4806c06bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gatsby-focus-wrapper']/div/div/main</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>main.landing-page</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=main</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>main</value>
      <webElementGuid>cadfb97e-fbe3-4240-a5b5-a3c0b9544d2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>landing-page</value>
      <webElementGuid>89167e43-d689-4b0b-9936-b0d18f3e2e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Learn to code — for free.Build projects.Earn certifications.Since 2014, more than 40,000 freeCodeCamp.org graduates have gotten jobs at tech companies including:AppleGoogleMicrosoftSpotifyAmazon Sign inGet started (it's free)As seen in:Wired, Business Insider, Inc. Magazine, Lifehacker, Time, Quartz, USA Today, The New York Times, BBCHere is what our alumni say about freeCodeCamp: Shawn Wang in SingaporeSoftware Engineer at Amazon&quot;It's scary to change careers. I only gained confidence that I could code by working through the hundreds of hours of free lessons on freeCodeCamp. Within a year I had a six-figure job as a Software Engineer. freeCodeCamp changed my life.&quot; Sarah Chima in NigeriaSoftware Engineer at ChatDesk&quot;freeCodeCamp was the gateway to my career as a software developer. The well-structured curriculum took my coding knowledge from a total beginner level to a very confident level. It was everything I needed to land my first dev job at an amazing company.&quot; Emma Bostian in SwedenSoftware Engineer at Spotify&quot;I've always struggled with learning JavaScript. I've taken many courses but freeCodeCamp's course was the one which stuck. Studying JavaScript as well as data structures and algorithms on freeCodeCamp gave me the skills and confidence I needed to land my dream job as a software engineer at Spotify.&quot; Sign inGet started (it's free)Earn free verified certifications with freeCodeCamp's core curriculum:1Responsive Web Design Certification2JavaScript Algorithms and Data Structures (Beta) Certification3Front End Development Libraries Certification4Data Visualization Certification5Relational Database Certification6Back End Development and APIs Certification7Quality Assurance Certification8Scientific Computing with Python (Beta) Certification9Data Analysis with Python Certification10Information Security Certification11Machine Learning with Python Certification12College Algebra with Python CertificationLearn English for Developers:A2 English for Developers (Beta) CertificationEarn free professional certifications:(New) Foundational C# with Microsoft CertificationPrepare for the developer interview job search:The Odin Project - freeCodeCamp Remix (Beta)Coding Interview PrepProject EulerRosetta CodeExplore our Legacy Curriculum:Legacy Responsive Web Design ChallengesLegacy JavaScript Algorithms and Data Structures CertificationLegacy Python for Everybody Sign inGet started (it's free)Frequently asked questions:What exactly is freeCodeCamp?freeCodeCamp is a community of people from all around the world who are learning to code together. We're a 501(c)(3) public charity.How will freeCodeCamp help me learn to code?You will learn to code by building dozens of projects, step-by-step, right in your browser, code editor, or mobile app.You will also earn free verified certifications along the way.Is freeCodeCamp really free?Yes. Every aspect of freeCodeCamp is 100% free. The courses, the projects, and even the certifications.Can freeCodeCamp help me get a job as a software developer?Yes. Every year, thousands of people who join the freeCodeCamp community get their first software developer job.What skills will I learn?You will learn the skills most developers use on the job: HTML, CSS, JavaScript, Python, Linux, Git, and SQL, and more. You'll also learn how to use powerful libraries for web development, mobile app development, data science, and artificial intelligence.How long does it take to learn all this?freeCodeCamp is self-paced. Realistically, it may take several years of practicing coding to learn these skills well enough to get a job as a software engineer. Don't quit school or your day job until you feel ready.How do I get started?If you're a beginner, you should start at the beginning of the freeCodeCamp core curriculum. If you're more advanced, we still recommend starting at the beginning, but you can skip to whatever area you wish.How do I earn the free verified certifications?For each certification, you need to build its 5 certification projects, and get all of the project tests to pass to be able to claim your certification.I don't see [name of tool] in the freeCodeCamp core curriculum.Aside from the freeCodeCamp core curriculum, We have thousands of free, full-length books, courses, and programming tutorials. We almost certainly teach whatever programming tools you want to learn. Just use the search bar.Happy coding! Sign inGet started (it's free)</value>
      <webElementGuid>0fdbf565-eea1-4816-8698-f0ee232a9b6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;page-wrapper&quot;]/div[@class=&quot;default-layout&quot;]/main[@class=&quot;landing-page&quot;]</value>
      <webElementGuid>3b1a4e0a-109d-4604-bf06-af89f61720e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div/main</value>
      <webElementGuid>5a84bfd6-c82e-4fe1-8d58-d731ac7939a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/following::main[1]</value>
      <webElementGuid>a5ac3a53-adf3-4459-be81-1b068ed1a03a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main</value>
      <webElementGuid>7016a7e4-003c-4f2c-b0fb-c46f3c6fd57d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//main[(text() = concat(&quot;Learn to code — for free.Build projects.Earn certifications.Since 2014, more than 40,000 freeCodeCamp.org graduates have gotten jobs at tech companies including:AppleGoogleMicrosoftSpotifyAmazon Sign inGet started (it&quot; , &quot;'&quot; , &quot;s free)As seen in:Wired, Business Insider, Inc. Magazine, Lifehacker, Time, Quartz, USA Today, The New York Times, BBCHere is what our alumni say about freeCodeCamp: Shawn Wang in SingaporeSoftware Engineer at Amazon&quot;It&quot; , &quot;'&quot; , &quot;s scary to change careers. I only gained confidence that I could code by working through the hundreds of hours of free lessons on freeCodeCamp. Within a year I had a six-figure job as a Software Engineer. freeCodeCamp changed my life.&quot; Sarah Chima in NigeriaSoftware Engineer at ChatDesk&quot;freeCodeCamp was the gateway to my career as a software developer. The well-structured curriculum took my coding knowledge from a total beginner level to a very confident level. It was everything I needed to land my first dev job at an amazing company.&quot; Emma Bostian in SwedenSoftware Engineer at Spotify&quot;I&quot; , &quot;'&quot; , &quot;ve always struggled with learning JavaScript. I&quot; , &quot;'&quot; , &quot;ve taken many courses but freeCodeCamp&quot; , &quot;'&quot; , &quot;s course was the one which stuck. Studying JavaScript as well as data structures and algorithms on freeCodeCamp gave me the skills and confidence I needed to land my dream job as a software engineer at Spotify.&quot; Sign inGet started (it&quot; , &quot;'&quot; , &quot;s free)Earn free verified certifications with freeCodeCamp&quot; , &quot;'&quot; , &quot;s core curriculum:1Responsive Web Design Certification2JavaScript Algorithms and Data Structures (Beta) Certification3Front End Development Libraries Certification4Data Visualization Certification5Relational Database Certification6Back End Development and APIs Certification7Quality Assurance Certification8Scientific Computing with Python (Beta) Certification9Data Analysis with Python Certification10Information Security Certification11Machine Learning with Python Certification12College Algebra with Python CertificationLearn English for Developers:A2 English for Developers (Beta) CertificationEarn free professional certifications:(New) Foundational C# with Microsoft CertificationPrepare for the developer interview job search:The Odin Project - freeCodeCamp Remix (Beta)Coding Interview PrepProject EulerRosetta CodeExplore our Legacy Curriculum:Legacy Responsive Web Design ChallengesLegacy JavaScript Algorithms and Data Structures CertificationLegacy Python for Everybody Sign inGet started (it&quot; , &quot;'&quot; , &quot;s free)Frequently asked questions:What exactly is freeCodeCamp?freeCodeCamp is a community of people from all around the world who are learning to code together. We&quot; , &quot;'&quot; , &quot;re a 501(c)(3) public charity.How will freeCodeCamp help me learn to code?You will learn to code by building dozens of projects, step-by-step, right in your browser, code editor, or mobile app.You will also earn free verified certifications along the way.Is freeCodeCamp really free?Yes. Every aspect of freeCodeCamp is 100% free. The courses, the projects, and even the certifications.Can freeCodeCamp help me get a job as a software developer?Yes. Every year, thousands of people who join the freeCodeCamp community get their first software developer job.What skills will I learn?You will learn the skills most developers use on the job: HTML, CSS, JavaScript, Python, Linux, Git, and SQL, and more. You&quot; , &quot;'&quot; , &quot;ll also learn how to use powerful libraries for web development, mobile app development, data science, and artificial intelligence.How long does it take to learn all this?freeCodeCamp is self-paced. Realistically, it may take several years of practicing coding to learn these skills well enough to get a job as a software engineer. Don&quot; , &quot;'&quot; , &quot;t quit school or your day job until you feel ready.How do I get started?If you&quot; , &quot;'&quot; , &quot;re a beginner, you should start at the beginning of the freeCodeCamp core curriculum. If you&quot; , &quot;'&quot; , &quot;re more advanced, we still recommend starting at the beginning, but you can skip to whatever area you wish.How do I earn the free verified certifications?For each certification, you need to build its 5 certification projects, and get all of the project tests to pass to be able to claim your certification.I don&quot; , &quot;'&quot; , &quot;t see [name of tool] in the freeCodeCamp core curriculum.Aside from the freeCodeCamp core curriculum, We have thousands of free, full-length books, courses, and programming tutorials. We almost certainly teach whatever programming tools you want to learn. Just use the search bar.Happy coding! Sign inGet started (it&quot; , &quot;'&quot; , &quot;s free)&quot;) or . = concat(&quot;Learn to code — for free.Build projects.Earn certifications.Since 2014, more than 40,000 freeCodeCamp.org graduates have gotten jobs at tech companies including:AppleGoogleMicrosoftSpotifyAmazon Sign inGet started (it&quot; , &quot;'&quot; , &quot;s free)As seen in:Wired, Business Insider, Inc. Magazine, Lifehacker, Time, Quartz, USA Today, The New York Times, BBCHere is what our alumni say about freeCodeCamp: Shawn Wang in SingaporeSoftware Engineer at Amazon&quot;It&quot; , &quot;'&quot; , &quot;s scary to change careers. I only gained confidence that I could code by working through the hundreds of hours of free lessons on freeCodeCamp. Within a year I had a six-figure job as a Software Engineer. freeCodeCamp changed my life.&quot; Sarah Chima in NigeriaSoftware Engineer at ChatDesk&quot;freeCodeCamp was the gateway to my career as a software developer. The well-structured curriculum took my coding knowledge from a total beginner level to a very confident level. It was everything I needed to land my first dev job at an amazing company.&quot; Emma Bostian in SwedenSoftware Engineer at Spotify&quot;I&quot; , &quot;'&quot; , &quot;ve always struggled with learning JavaScript. I&quot; , &quot;'&quot; , &quot;ve taken many courses but freeCodeCamp&quot; , &quot;'&quot; , &quot;s course was the one which stuck. Studying JavaScript as well as data structures and algorithms on freeCodeCamp gave me the skills and confidence I needed to land my dream job as a software engineer at Spotify.&quot; Sign inGet started (it&quot; , &quot;'&quot; , &quot;s free)Earn free verified certifications with freeCodeCamp&quot; , &quot;'&quot; , &quot;s core curriculum:1Responsive Web Design Certification2JavaScript Algorithms and Data Structures (Beta) Certification3Front End Development Libraries Certification4Data Visualization Certification5Relational Database Certification6Back End Development and APIs Certification7Quality Assurance Certification8Scientific Computing with Python (Beta) Certification9Data Analysis with Python Certification10Information Security Certification11Machine Learning with Python Certification12College Algebra with Python CertificationLearn English for Developers:A2 English for Developers (Beta) CertificationEarn free professional certifications:(New) Foundational C# with Microsoft CertificationPrepare for the developer interview job search:The Odin Project - freeCodeCamp Remix (Beta)Coding Interview PrepProject EulerRosetta CodeExplore our Legacy Curriculum:Legacy Responsive Web Design ChallengesLegacy JavaScript Algorithms and Data Structures CertificationLegacy Python for Everybody Sign inGet started (it&quot; , &quot;'&quot; , &quot;s free)Frequently asked questions:What exactly is freeCodeCamp?freeCodeCamp is a community of people from all around the world who are learning to code together. We&quot; , &quot;'&quot; , &quot;re a 501(c)(3) public charity.How will freeCodeCamp help me learn to code?You will learn to code by building dozens of projects, step-by-step, right in your browser, code editor, or mobile app.You will also earn free verified certifications along the way.Is freeCodeCamp really free?Yes. Every aspect of freeCodeCamp is 100% free. The courses, the projects, and even the certifications.Can freeCodeCamp help me get a job as a software developer?Yes. Every year, thousands of people who join the freeCodeCamp community get their first software developer job.What skills will I learn?You will learn the skills most developers use on the job: HTML, CSS, JavaScript, Python, Linux, Git, and SQL, and more. You&quot; , &quot;'&quot; , &quot;ll also learn how to use powerful libraries for web development, mobile app development, data science, and artificial intelligence.How long does it take to learn all this?freeCodeCamp is self-paced. Realistically, it may take several years of practicing coding to learn these skills well enough to get a job as a software engineer. Don&quot; , &quot;'&quot; , &quot;t quit school or your day job until you feel ready.How do I get started?If you&quot; , &quot;'&quot; , &quot;re a beginner, you should start at the beginning of the freeCodeCamp core curriculum. If you&quot; , &quot;'&quot; , &quot;re more advanced, we still recommend starting at the beginning, but you can skip to whatever area you wish.How do I earn the free verified certifications?For each certification, you need to build its 5 certification projects, and get all of the project tests to pass to be able to claim your certification.I don&quot; , &quot;'&quot; , &quot;t see [name of tool] in the freeCodeCamp core curriculum.Aside from the freeCodeCamp core curriculum, We have thousands of free, full-length books, courses, and programming tutorials. We almost certainly teach whatever programming tools you want to learn. Just use the search bar.Happy coding! Sign inGet started (it&quot; , &quot;'&quot; , &quot;s free)&quot;))]</value>
      <webElementGuid>6df1fc3c-25a3-41f4-bace-dac617075707</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
