<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Looking for results in EnglishChange to_6e6c03</name>
   <tag></tag>
   <elementGuidId>47ed868e-a24b-43aa-a6c7-af97d16014af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='slim_appbar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#slim_appbar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#slim_appbar</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>972403d8-ae80-4dcb-8f74-148c44d21435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>WE0UJf</value>
      <webElementGuid>54727de3-266a-4311-80a6-053da075ed93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>slim_appbar</value>
      <webElementGuid>328f6642-b522-4fd8-829b-92a3f89f9e40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Looking for results in English?Change to EnglishTiếp tục sử dụng Tiếng ViệtCài đặt ngôn ngữ</value>
      <webElementGuid>8282ca17-542d-4149-9605-bbd0bcffaeb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slim_appbar&quot;)</value>
      <webElementGuid>35a532da-0993-4081-ba24-c767ba732c4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='slim_appbar']</value>
      <webElementGuid>ad73f3d5-e74a-4d94-aab8-57f20deaecfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tU52Vb']/div/div</value>
      <webElementGuid>32cd7f52-94d5-46f0-bfbf-71c48d4d31d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div/div</value>
      <webElementGuid>de73134b-db3e-468c-9b12-ee39dcecda92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'slim_appbar' and (text() = 'Looking for results in English?Change to EnglishTiếp tục sử dụng Tiếng ViệtCài đặt ngôn ngữ' or . = 'Looking for results in English?Change to EnglishTiếp tục sử dụng Tiếng ViệtCài đặt ngôn ngữ')]</value>
      <webElementGuid>a9ee17b1-c2bd-4e86-9e25-47dca2d02abd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
