<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Khng tm thy lkjasdlfkjalsdkj at 1023.20.n_6c4b6e</name>
   <tag></tag>
   <elementGuidId>db30d27f-a361-4a7c-977c-738199cd9364</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='botstuff']/div/div[2]/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Không tìm thấy lkjasdlfkjalsdkj at 1023.20.:not found lalskjdf.jssssssss:33030923 trong tài liệu nào.&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>b915b94a-0156-48f1-bf74-00f2065c1179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-level</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>24b9cba5-3abb-4a2b-a6a6-3c4aac130c17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>cc584085-d95e-49f1-ae2b-8ec8ea7e8117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Không tìm thấy lkjasdlfkjalsdkj at 1023.20.:not found lalskjdf.jssssssss:33030923 trong tài liệu nào.</value>
      <webElementGuid>50f47e8f-8ec9-4103-8e4f-2e167dfe92e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;botstuff&quot;)/div[1]/div[@class=&quot;mnr-c&quot;]/div[@class=&quot;card-section&quot;]/p[1]</value>
      <webElementGuid>682e4843-5558-4bb9-8be1-13ef49cf8c95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='botstuff']/div/div[2]/div/p</value>
      <webElementGuid>c45a4b72-5d05-4e0b-beb2-c55ddba81572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Điều khoản'])[1]/following::p[1]</value>
      <webElementGuid>5c5bf24d-3b13-4d99-bd45-c7603826aafa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quyền riêng tư'])[1]/following::p[1]</value>
      <webElementGuid>39250ab9-71d2-4044-9ca1-2b55d37196c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xin bạn chắc chắn rằng tất cả các từ đều đúng chính tả.'])[1]/preceding::p[2]</value>
      <webElementGuid>c65a8ac0-72ba-4748-a71c-a5766aa61f90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Không tìm thấy']/parent::*</value>
      <webElementGuid>e9357bae-9f18-42af-a429-7e7b78774e91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>3f7a6135-e291-4c39-819f-3eb0a0f6918b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Không tìm thấy lkjasdlfkjalsdkj at 1023.20.:not found lalskjdf.jssssssss:33030923 trong tài liệu nào.' or . = 'Không tìm thấy lkjasdlfkjalsdkj at 1023.20.:not found lalskjdf.jssssssss:33030923 trong tài liệu nào.')]</value>
      <webElementGuid>b68238cc-84af-46a6-9b74-8e9418fa9378</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
