<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_iPhone 12</name>
   <tag></tag>
   <elementGuidId>3c7e4df7-15c6-4711-8016-c843aec1aa7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='filter-follow-manu']/a[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#filter-follow-manu >> internal:role=link[name=&quot;iPhone 12&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>eb4b6c63-6d9f-4f1c-ae37-8c9bf4685ecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>dtdd-apple-iphone-12-series</value>
      <webElementGuid>4e29c037-bcc2-4679-bb36-294355b306d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-manuid</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>2ffdc093-9144-432e-9e63-e2a60a1a934b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-smooth</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>18e00fd6-7e5a-4eca-a026-41b89f871e78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-href</name>
      <type>Main</type>
      <value>12-series</value>
      <webElementGuid>70305a94-f1ef-4c4e-96cc-31b582b4093a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>180894</value>
      <webElementGuid>6888c239-425a-4a11-9989-6073b45dad2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-btnbox </value>
      <webElementGuid>ee1a53ba-3899-4e8e-95ba-268bffd5087f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>iPhone 12</value>
      <webElementGuid>3ab15f65-19cf-49fe-a1a4-6c0203f0ecfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filter-follow-manu&quot;)/a[@class=&quot;c-btnbox&quot;]</value>
      <webElementGuid>7b66f584-d2e9-4266-8c22-083572e2b928</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filter-follow-manu']/a[4]</value>
      <webElementGuid>00139abc-def0-4109-ae8f-f3381913ca0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'iPhone 12')]</value>
      <webElementGuid>dcb2cf7c-ee94-42fc-9dd7-bcf690efaf4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='iPhone 13'])[1]/following::a[1]</value>
      <webElementGuid>2a68ab39-645e-4766-8dd6-0907de052b17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='iPhone 14 (Plus, Pro, Pro Max)'])[1]/following::a[2]</value>
      <webElementGuid>43516fb3-235b-48dd-991d-daa4f9c59566</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='iPhone 11'])[1]/preceding::a[1]</value>
      <webElementGuid>27765475-979b-4818-8b4e-fd91e75dee9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='iPhone (Apple)'])[3]/preceding::a[2]</value>
      <webElementGuid>5ae7e1cb-f832-4947-9b2c-8987cf2f046d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='iPhone 12']/parent::*</value>
      <webElementGuid>f9cb5a25-e3df-46a5-a905-202247dc52ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'dtdd-apple-iphone-12-series')]</value>
      <webElementGuid>13dae523-1709-4100-b400-cb01555a15a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a[4]</value>
      <webElementGuid>c2e18918-1817-4e32-9ebc-f2b2dd03bfd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'dtdd-apple-iphone-12-series' and (text() = 'iPhone 12' or . = 'iPhone 12')]</value>
      <webElementGuid>3d1bec6e-0af4-40f5-8a98-02bbdfa118dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
