<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sau</name>
   <tag></tag>
   <elementGuidId>b0ba37a0-f75f-4688-b8c9-9aa0282db708</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='paging']/a[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Sau&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>058b3ba4-9823-4824-a35b-8e0864d81e53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/tim-kiem.chn?keyword=liên minh&amp;page=2</value>
      <webElementGuid>02f96de9-fcf5-4278-8ab1-0b08d0ab71d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>1a55e8cc-0f36-4b00-afff-74c81c795402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Sau </value>
      <webElementGuid>ff71589f-a402-4068-a9b8-0ea7890e9b5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paging&quot;)/a[@class=&quot;number&quot;]</value>
      <webElementGuid>ea02ee03-c1f5-4132-a798-1cf22f72303f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='paging']/a[6]</value>
      <webElementGuid>2cec9134-e68b-4fd3-b444-52422e84abce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sau')]</value>
      <webElementGuid>6d43bc29-aa51-40e0-a4be-6e1c96cdcd71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='...'])[1]/following::a[1]</value>
      <webElementGuid>290cf550-e72d-4e68-a395-800ac105f9f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ấn tượng với những tuyển thủ góp mặt nhiều nhất tại các kì CKTG Liên Minh Huyền Thoại'])[1]/following::a[6]</value>
      <webElementGuid>e63f3ea9-20c3-4e61-ae2a-ee846bffa7ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tin mới'])[1]/preceding::a[1]</value>
      <webElementGuid>26d2adc5-6d9c-4cfd-8371-1e2f462a7952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='One Piece: Sau Gear 5, Luffy có thể theo bước một vị thần khác để mạnh hơn'])[1]/preceding::a[3]</value>
      <webElementGuid>ae563171-1268-4667-a91a-fee4d9b4f6a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sau']/parent::*</value>
      <webElementGuid>3e22b19f-e40a-4326-8ee2-77a5072b7401</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/tim-kiem.chn?keyword=liên minh&amp;page=2')])[2]</value>
      <webElementGuid>7a3b2f80-3843-4de0-888a-560fce034895</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[6]</value>
      <webElementGuid>0a9952eb-10c1-4f99-a4a8-fe0348b9a5fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/tim-kiem.chn?keyword=liên minh&amp;page=2' and (text() = ' Sau ' or . = ' Sau ')]</value>
      <webElementGuid>b94f376f-7901-40ca-a7d7-38d7108268d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
