<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_H Ch Minh_key</name>
   <tag></tag>
   <elementGuidId>dbce7ec9-0b31-4825-a835-0f78866c8b41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#skw</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='skw']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Bạn tìm gì...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5c8ee52a-9484-4e72-bd12-5a821c8940ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>skw</value>
      <webElementGuid>9a06a8bc-192b-4910-9823-6caf514a78c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>34dce539-4ab2-4a29-b7c7-40aec93eb169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-search</value>
      <webElementGuid>d0189a7b-9a6e-480d-a763-a23019035592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>suggestSearch(event);</value>
      <webElementGuid>e0ce1cad-3d3a-4d97-8e8b-a690cea5b599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Bạn tìm gì...</value>
      <webElementGuid>c4ee62c0-d6a6-4eab-9bc4-eb67592a4beb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>key</value>
      <webElementGuid>6767d00b-5e36-4106-b632-407bbdae0d9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4ee8f0be-5970-4eb1-807f-0d23541cfebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>5cd49b82-72c0-409b-9f4c-45145b268c11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;skw&quot;)</value>
      <webElementGuid>fcd34d81-6886-44d9-96e3-e3903350fb73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='skw']</value>
      <webElementGuid>3b33b075-ea5d-4217-b440-ad3f91772d88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>1289656b-5e0f-4193-8854-e23ecae94a6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'skw' and @type = 'text' and @placeholder = 'Bạn tìm gì...' and @name = 'key']</value>
      <webElementGuid>79d9505f-6e81-4174-a41c-7957b0cabba2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
