<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__key</name>
   <tag></tag>
   <elementGuidId>5710a4b4-3105-487c-91c7-c5c3e9c6c496</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inp-search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inp-search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Bạn cần tìm gì...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>83dd1e98-c839-4660-a2ea-150d9513c77f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>color-white</value>
      <webElementGuid>7d7fe129-38d1-4320-8bc5-91fb6f029208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inp-search</value>
      <webElementGuid>4961a104-dbca-42f7-aed6-e64c32f60100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f4bd4f0b-984a-4bec-ab0b-dfaea38ab79e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>key</value>
      <webElementGuid>3e66c864-8a30-4cf0-aa78-2d5d52ddd307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Bạn cần tìm gì...</value>
      <webElementGuid>f170214f-76f2-4c1d-bae7-eb2a2fc3ee31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9d40c256-fcb2-4cfd-b204-402d659cc51a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Bạn cần tìm gì...</value>
      <webElementGuid>b9c7a2a0-8abe-45a2-9383-fde25a5e5e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Bạn cần tìm gì...</value>
      <webElementGuid>8b2a78b0-27ab-490d-92af-ed34972cfc00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inp-search&quot;)</value>
      <webElementGuid>0f08304f-8005-47d7-9d81-1322ed662268</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inp-search']</value>
      <webElementGuid>61e6d6a2-0dcc-4bac-9ed0-a2a62a78cb29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>0137c275-46d4-439e-99a2-bb0487e0faf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inp-search' and @type = 'text' and @name = 'key' and @placeholder = 'Bạn cần tìm gì...' and @title = 'Bạn cần tìm gì...']</value>
      <webElementGuid>494e6086-47f9-4eec-9143-5642414a8f11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
