<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Xemkt qu_no-text</name>
   <tag></tag>
   <elementGuidId>7ca172cf-7e1d-408b-8e9c-f2ad54b14f5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/a[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.lst-quickfilter > a:nth-child(2) >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b41950be-a83d-4528-b42b-18fda4e51cfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//cdn.tgdd.vn/Brand/1/logo-iphone-220x48.png</value>
      <webElementGuid>dc2d743f-6375-41bc-aac3-64b51ffbee1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>bd5d128a-2bd5-4464-a663-82a3611c7500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>no-text</value>
      <webElementGuid>a140ec37-0245-418e-a09e-611828eaf719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;&quot;]/div[6]/div[@class=&quot;box-filter top-box  block-scroll-main cate-42&quot;]/section[1]/div[@class=&quot;box-quicklink  block-scroll-main&quot;]/div[@class=&quot;lst-quickfilter q-manu&quot;]/a[@class=&quot;box-quicklink__item bd-radius quicklink-logo&quot;]/img[@class=&quot;no-text&quot;]</value>
      <webElementGuid>fbb61f7d-e958-422b-a5f1-7ddf7df7601a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a[2]/img</value>
      <webElementGuid>255e9b75-41c6-4ad0-b391-1c3670b0a469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//cdn.tgdd.vn/Brand/1/logo-iphone-220x48.png']</value>
      <webElementGuid>4f1d44f0-4837-425c-bf1b-8110e3f22aca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
