<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_RSS_mb10</name>
   <tag></tag>
   <elementGuidId>5b42f55e-14ba-4ef0-a3fe-78557d5d5b91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='admWrapsite']/div[2]/div[2]/div/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.mb10</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Công ty cổ phần VCCorp&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2a5dfdb9-ef98-48e2-8359-7abd7ab977b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://vccorp.mediacdn.vn/vccorp-s.png</value>
      <webElementGuid>db9aed5a-1212-4f7b-ba37-672a823f6655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Công ty cổ phần VCCorp</value>
      <webElementGuid>97237878-cec5-440e-8c71-d6fe348d2551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb10</value>
      <webElementGuid>2e40a09f-ddbc-4750-bdd9-7bb5f7e38b2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;admWrapsite&quot;)/div[@class=&quot;footer fl&quot;]/div[@class=&quot;info&quot;]/div[@class=&quot;wp980-mauto&quot;]/div[@class=&quot;left_info&quot;]/a[1]/img[@class=&quot;mb10&quot;]</value>
      <webElementGuid>79485457-2a3f-488d-99ac-6e3dc5b75cdf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='admWrapsite']/div[2]/div[2]/div/div/a/img</value>
      <webElementGuid>a05ee8da-5c77-4d03-a40f-a191abd2666a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Công ty cổ phần VCCorp']</value>
      <webElementGuid>d30d2e27-0330-40b5-90b6-a81db6cb97f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/a/img</value>
      <webElementGuid>bf0f4d5a-9f93-4ec9-9a0b-b2e399eff95c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://vccorp.mediacdn.vn/vccorp-s.png' and @alt = 'Công ty cổ phần VCCorp']</value>
      <webElementGuid>daf9505a-3798-4aa4-87f2-b73b413ee0f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
